README.md

Simple fixes in the README.md
1. Added more comments to the python snippets
2. Fixed Capitalization
3. Fixed Grammar
4. Fixed Spacing
-----------------
Even though some of the comments that I added to the python snippets restate existing documentation, some people are will pay more attention to the comments than to the documentation. I also standardized the spacing and put a blank line under every import block.

README fixing

---

appveyor.yml

Previously PRs would all fail due to secrets (specifically for coveralls) not being available on builds for external repos.

Fix CI for external PRs

---

ahk/keyboard.py

Fixes #36. Functions send and send_raw were returning empty strings. Now returns `None`.

Fix empty string bug from send/send_raw

---

ahk/screen.py
ahk/templates/screen/image_search.ahk

Added in the rest of the image search function options. https://www.autohotkey.com/docs/commands/ImageSearch.htm
- *n (color variation): Allows the search to be more lenient with the colors in the image that it is looking for. The minimum input of 0 will cause the search to match only if all the pixel colors are exactly the same, while the maximum input of 255 will cause the search to match the pixels with any color.
- *TransN (transparent): The search ignores pixels that have the value that is passed. By editing trivial portions of the image out with a single color, only the untouched parts will be considered.
- *IconN (icon): Changes the icon group number to be used.

Add missing image search options

---

ahk/script.py
tests/unittests/test_executable_location.py

Provides some extra safety when misconfiguring `executable_path` argument.
Related to #69 and #32

Executable path safety

---

appveyor.yml

In #49 I accidentally replaced `coveralls` with `coverage` -- causing coverage report integration with coveralls.io to stop working. This restores coverage reporting.

restore coveralls command

---

ahk/keyboard.py

Adds optional parameter to make keyboard functions non-blocking. By default, the behavior is (and always has been) to block.

add (non)blocking parameter for keyboard functions

---

ahk/templates/window/win_send.ahk
ahk/window.py

`Window.send` has `delay` as a kwarg and was even passing it to the template in the Python logic, but the actual `window/win_send.ahk` template didn't have the conditional logic to set the key delay.

Adding 'delay' and 'press_duration' logic to the 'window/win_send.ahk' AHK template

---

ahk/registery.py

Renames `read`/`write`/`delete`/`set_view` to `reg_read`/`reg_write`/`reg_delete`/`reg_set_view`

add deprecation warnings for renamed registry methods

---

ahk/templates/keyboard/key_state.ahk

key_state was not able to identify a toggled state due to missing quotations around the mode argument. 
modification made to key_state.ahk template

quotation marks added mode place holder

---

ahk/script.py
docs/README.md

Adds `directives` argument to script engine, allowing directives to be added to all generated scripts.
```python
from ahk import AHK
from ahk.directives import NoTrayIcon
ahk = AHK(directives=[NoTryIcon])
```

Directives

---

ahk/__init__.py
ahk/autohotkey.py
ahk/gui.py
ahk/keyboard.py
ahk/mouse.py
ahk/registry.py
ahk/screen.py
ahk/script.py
ahk/sound.py
ahk/templates/window/win_click.ahk
ahk/templates/window/win_position.ahk
ahk/utils.py
ahk/window.py
appveyor.yml
ci/install.bat
docs/README.md
setup.py
tests/unittests/test_keyboard.py
tests/unittests/test_keyboard_async.py
tests/unittests/test_mouse.py
tests/unittests/test_screen_async.py
tests/unittests/test_win_get_async.py
tests/unittests/test_window_async.py

Adds base asyncio support.
While the existing user-facing APIs remains mostly untouched, there are some significant and potentially breaking changes in the PR:
* Default parameter of `blocking` for a couple functions is changed from `False` to `True`  
* Internal API has shifted around quite a bit. Template generation and script running have been split in all (or most) methods  
* Typos in classes and modules were corrected (registry.py and RegistryMixin)
Still to come (in future PRs):
* async hotkeys with Python callbacks!
* A performance-optimized "daemon" mode, where commands are run in a single process, instead of invoking a new process for each AHK command

Asyncio support (preview)

---

ahk/daemon.py
ahk/templates/_daemon.ahk
ahk/templates/daemon.ahk
tests/unittests/test_daemon.py
tests/unittests/test_daemon_async.py

Currently, the (async) daemon does not correctly handle responses containing a newline (for example, when retrieving the text of a window that contains multiple lines). By accidental implementation detail, the synchronous daemon does not have this problem.
Adds new protocol in order to handle responses that contain multiple lines.
The protocol essentially works like this:
1. The request is sent as a command, terminated by a newline, to the stdin of the AHK daemon process. Commands never contain literal newlines.
2. The daemon will read the command from stdin to determine which function to execute (so far, this is the same as previously)
3. AHK will count the number of newlines in the response, then send that number to stdout, terminated by a newline, followed by the payload, terminated by …

Daemon protocol to fix multiline response handling

---

ahk/templates/_daemon.ahk
ahk/templates/daemon.ahk
ahk/templates/daemon/win_wait.ahk
ahk/templates/window/win_wait.ahk
ahk/window.py
docs/README.md
tests/unittests/test_daemon_async.py
tests/unittests/test_win_get.py
tests/unittests/test_win_get_async.py
tests/unittests/test_window.py
tests/unittests/test_window_async.py

Resolves #131 
Resolves a few key inconsistencies in the `find_window` and `win_get` APIs.
- `win_get` will now return `None` (instead of a Window object with its ID as `None`)
- `find_window` in the async API returns None if no window is found (to match the sync API. The Async API previously would raise an exception instead)
- the `Window.wait` method is removed. 
- the `win_wait` method is implemented
`win_wait` works like this:
```python
from ahk import AHK
ahk = AHK()
try:
notepad = ahk.win_wait(title='Untitled - Notepad', timeout=5) # wait up to 5 seconds for notepad
except TimeoutError:
print('Notepad was not found!')
```

Implement win_wait and make win_get consistent with find_window

---

ahk/script.py

Resolves #132 
This also impacts related issues like #146 and #45
Setting the codepage explicitly means that scripts sent to AHK are correctly interpreted as UTF-8
This means UTF-8 text will be able to be sent with methods like `send`, `send_input`, etc and be correctly interpreted.
This does not affect behavior in the case where Daemon mode is used (AHK still interprets stdin using system encoding). In which case, the workaround of using unicode escape sequences is required.

Add UTF-8 codepage explicitly

---

ahk/templates/_daemon.ahk
ahk/templates/asynchotkey.ahk
ahk/templates/daemon.ahk
ahk/templates/keyboard/key_state.ahk
ahk/templates/keyboard/key_wait.ahk
ahk/templates/mouse/mouse_position.ahk
ahk/templates/registery/reg_read.ahk
ahk/templates/screen/image_search.ahk
ahk/templates/screen/pixel_get_color.ahk
ahk/templates/screen/pixel_search.ahk
ahk/templates/sound/get_volume.ahk
ahk/templates/sound/sound_get.ahk
ahk/templates/sound/sound_set.ahk
ahk/templates/window/base_check.ahk
ahk/templates/window/base_get_command.ahk
ahk/templates/window/from_mouse.ahk
ahk/templates/window/get.ahk
ahk/templates/window/id_list.ahk
ahk/templates/window/title_list.ahk
ahk/templates/window/win_is_always_on_top.ahk
ahk/templates/window/win_position.ahk
ahk/templates/window/win_wait.ahk
docs/README.md

Followup to #150 -- this change should cover the outputs send back from AHK.
It should also make `encoding` parameters obsolete.

specify UTF8 for all outputs

---

.github/workflows/release.yaml
ahk/_async/engine.py
ahk/_async/transport.py
ahk/_constants.py
ahk/_sync/engine.py
ahk/_sync/transport.py
ahk/templates/daemon.ahk
docs/README.md
docs/conf.py

New features:
- `menu_tray_icon` allows users to change tray icon
- `menu_tray_tooltip` allows users to change the tray icon tooltip
- `menu_tray_icon_show` allows users to show the tray icon if it was previously hidden by `NoTrayIcon` directive.

Add menu tray icon commands

---

.pre-commit-config.yaml
.unasync-rewrite.py
pyproject.toml
setup.cfg

Update for including new version of `unasync` which will support `unasync: remove` comments -- so the custom logic can be removed from this project.
Should also allow us to use `python -m build` correctly (instead of needing to do `python setup.py sdist bdist_wheel`
Resolves #195

unasync changes

---

ahk/_async/engine.py
ahk/_constants.py
ahk/_sync/engine.py
ahk/templates/daemon.ahk
tests/_async/test_screen.py
tests/_sync/test_screen.py

Resolves #199 
Squashed a bug where the image path is not passed to AHK when any of the keyword arguments to `image_search` which map to `ImageFile` options for `ImageSearch`  (e.g., `color_variation`,  `scale_height`, `transparent`, etc.) are provided.
Also includes a few other bug fixes:
- fixes the coord_mode argument for `ImageSearch` (previously ignored)
- fixes a bug where global state can be erroneously changed (not reverted) in the AHK implementation for `win_set_trans_color`
- fixes a bug where global state modifiers are not respected for the AHK implementation for `win_close`

#199 - ensure image path is always passed in image_search

---

ahk/_async/transport.py
ahk/_sync/transport.py

A small change to improve error messages raised when a protocol error occurs.
Specifically:
1. `AHKProtocolError` is now raised `from` the original ValueError exception
2. non-blocking requests now raise `AHKProtocolError` instead of `ValueError`

Improve protocol error messaging

---

ahk/_async/engine.py
ahk/_async/transport.py
ahk/_hotkey.py
ahk/_sync/engine.py
ahk/_sync/transport.py
docs/README.md
setup.cfg
tests/_async/test_hotkeys.py
tests/_async/test_keys.py
tests/_sync/test_hotkeys.py
tests/_sync/test_keys.py

Resolves #213 
Adds new methods for removing hotstrings/hotkeys:
- `remove_hotkey` to remove a hotkey by keyname
- `clear_hotkeys` to remove all hotkeys
- `remove_hotstring` to remove a hotstring by trigger sequence
- `clear_hotstrings` to clear all hotstrings
Like adding hotkeys or hotstrings, using these methods while the hotkey process is already running causes a restart of the hotkey process.
----
During testing, a bug was discovered in which a race condition existed if you tried to stop hotkeys too soon after starting them. The dispatcher thread is responsible for creating the subprocess, but because this happens asynchronously it's not guaranteed that the subprocess has started by the time `stop` is called.
As a temporary fix for this bug, the stop process will wait _up to_ 1 second …

add methods for removing hotkeys and hotstrings

---

ahk/_async/transport.py
ahk/_constants.py
ahk/_hotkey.py
ahk/_sync/transport.py
ahk/directives.py
ahk/templates/hotkeys.ahk
docs/README.md
setup.cfg

Resolves #211 
Related to #216 
Adds the ability for directives to be specified for the hotkey process.
----
Proposed interface:
For any directive, add the keyword `apply_to_hotkeys_process=True` to have the directive apply to the hotkey/hotstring process.
```python
from ahk.directives import NoTrayIcon
directives = [
NoTrayIcon(apply_to_hotkeys_process=True)
]
ahk = AHK(directives=directives)
```
----
Technically this leaks an implementation detail into the abstraction, but we can fix that in a v2 release if needed. For now, I think practicality beats purity.

Allow directives to be specified for hotkey process

---

ahk/__init__.py
ahk/_async/engine.py
ahk/_async/transport.py
ahk/_async/window.py
ahk/_constants.py
ahk/_sync/engine.py
ahk/_sync/transport.py
ahk/_sync/window.py
ahk/_utils.py
ahk/templates/daemon.ahk
tests/_async/test_gui.py
tests/_sync/test_gui.py

This PR adds some of the GUI methods from AutoHotkey. Namely:
- `msg_box` as an analog for AHK's `MsgBox`
- `input_box` as an analog for AHK's `InputBox`
- `file_select_box` as an analog for AHK's `FileSelectFile`
- `folder_select_box` as an analog for AHK's `FileSelectFolder`
This PR does _not_ implement the broader `Gui` functions. Because AHK lacks true threading, while AHK is reading stdin for new commands, no other activity can occur in the AHK process. This means that GUI dialogs will fail to respond to user input (causing Windows to indicate 'the application is not responding'). This could be worked around in a similar manner to how we handle hotkeys in a separate process for the same reason -- however, this is decidedly not planned. Python has far more robust options for GUI …

gui methods

---

.pre-commit-config.yaml
ahk/message.py

A simple fix for a typing issue that was surfaced when upgrading to `mypy` version 1.5.1 where the (abstract) base `ResponseMessage` class was included in the message. The base class is now removed from the registry by default. Since that message type can never be unpacked anyhow (even if the class could be instantiated), this shouldn't cause any incompatibility with previous versions.
Supersedes #227

exclude abstract base class from message registry

---

ahk/_constants.py
ahk/_hotkey.py
ahk/templates/daemon-v2.ahk
ahk/templates/daemon.ahk
ahk/templates/hotkeys-v2.ahk
ahk/templates/hotkeys.ahk
docs/README.md

Resolves #257 
Normally, when Python exits it will cleanup any of the AHK subprocesses that were created. This is handled by `atexit` handlers. However, if the Python process is terminated abruptly in a manner that prevents `atexit` handlers from running, the AHK process(es) will not be reaped and will continue running (or in the case of AHK v2, the daemon will throw an error then exit).
This PR changes the AHK daemon script logic to call `ExitApp` to exit gracefully in the case where the parent Python process exits unexpectedly (instead of continuing the loop endlessly in v1 or raising an error message in v2). This is done by assuming that when `stdin.ReadLine()` returns empty it is because the parent Python process died. This is the only case where the message is known to be empty. …

Add AHK process handling to exit if parent Python process dies unexpectedly

---

ahk/_async/engine.py
ahk/_constants.py
ahk/_sync/engine.py
ahk/templates/daemon-v2.ahk

Fixes a bug (not passing required number of arguments) in the `mouse_drag` function that caused the function to error when used with AutoHotkey version 2. Also fixes subsequent API incompatibilities between AHK v1 and v2.
Resolves #264

GH-264 fix mouse_drag error when using AutoHotkey v2

---

ahk/_async/engine.py
ahk/_sync/engine.py

Resolves #277 
When using the `key_state` method with AutoHotkey v2, when the `mode` keyword argument is omitted, this produces an error. The argument array becomes undersized and, in AutoHotkey v2, this produces an error when trying to access the argument.

fix key_state for AHKv2 when no mode argument is given

---

ahk/_async/engine.py
ahk/_sync/engine.py
tests/_async/test_window.py
tests/_sync/test_window.py

Fix detect hidden windows for AutoHotkey v2

---

ahk/_async/engine.py
ahk/_sync/engine.py

Fixes a problem where `msg_box` has missing arguments for the underlying call to AHKMsgBox, which results in an error being thrown when using AHKv2.
Resolves #289

GH-289 fix message box in AHKv2

---

ahk/_async/engine.py
ahk/_sync/engine.py

When the `wait_for_any_data` keyword is omitted from `clip_wait`, in AutoHotkey v2, an error is thrown. This PR resolves this issue by ensuring the proper number of arguments are passed.

fix clip_wait in AHKv2

---

ahk/__init__.py
ahk/_async/engine.py
ahk/_async/transport.py
ahk/_async/window.py
ahk/_sync/engine.py
ahk/_sync/transport.py
ahk/_sync/window.py
ahk/_types.py
ahk/message.py

- `mouse_position`, `get_mouse_position`, `pixel_search`, and `image_search` now return a `Coordinates` named tuple (`typing.NamedTuple`) type instead of just a plain `tuple[int, int]`.
- Refactored types shared between sync and async into a common, internal, `_types` module.
- The `Position` type is now created using `typing.NamedTuple` rather than `collections.namedtuple`.
- Exposes more types directly via `__init__.py` so they can be imported without reaching into internal modules.

typing improvements

---

.unasync-rewrite.py

https://github.com/psf/black/pull/4270 changed `black.assert_equivalent` to raise an `ASTSafetyError` exception (a custom exception inheriting from `Exception`) so catching `AssertionError` no longer works when developing with recent versions of `black`
This change makes the code compatible with older and newer versions of `black`.

fix bug where `black.assert_equivalent` no longer raises an AssertionError

---

docs/api/methods.rst

PySimpleGUI is no longer open source, so it can no longer in good conscience be recommended. Its open LGPL fork replacement is recommended instead.

Remove recommendation for psg, since it is no longer open source

---

ahk/_constants.py
ahk/templates/daemon-v2.ahk

This fixes a bug that occurs when using AHKv2 when using the `send` method (or other relevant methods like `send_input`, `send_play`, etc.) when only providing _either_ `key_delay` _or_ `key_press_duration`.
Resolves #315

GH-315 fix usage of SetKeyDelay in AHKv2

---

ahk/_async/engine.py
ahk/_async/transport.py
ahk/_sync/engine.py
ahk/_sync/transport.py

Improves daemon start behavior by deferring start until the first _blocking_ call. This allows non-blocking calls to be used without starting the daemon process.

Improve start behavior

---

ahk/_hotkey.py
tests/_async/test_keys.py
tests/_sync/test_keys.py

Resolves GH-328
Hotkey scripts are generated using `tempfile.NamedTemporaryFile`, but this currently lacks a specified `encoding`, which results in the local encoding (i.e. `locale.getencoding()`) being used, which will likely produce problems.
When the hotstring characters are not valid in the local default encoding, the script generation can fail:
```py
ahk.add_hotstring('тест', 'hello world!')
ahk.start_hotkeys()
```
```py
Exception in thread Thread-3 (listener):
Traceback (most recent call last):
File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
self.run()
File "C:\Python310\lib\threading.py", line 946, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\Spencer\repos\ahk\ahk\_hotkey.py", line 327, in listener
f.write(hotkey_script_contents)
File …
```

Ensure correct encoding for hotkeys scripts

---

ahk/_async/transport.py
ahk/_sync/transport.py
buildunasync.py

As described in #338 use of `atexit.register` in `AsyncAHKProcess` causes a reference to be held for the subprocess. In use cases that make heavy use of `run_script` or calls with `blocking=False`, this can lead to buildup of memory. The rate of growth can be dependent on the size of the value returned by the script and how often it is called.
This PR fixes this issue by avoiding the need for `atexit.register` for these two scenarios. `atexit.register` is still used for the long-running daemon process to ensure cleanup.

GH-338 allow garbage collection of non-daemon processes

---

ahk/_async/engine.py
ahk/_constants.py
ahk/_sync/engine.py
ahk/templates/daemon-v2.ahk

Bringing #353 into main with fixes to allow CI to pass

Fix unset argument behavior on various functions

---

ahk/_async/engine.py
ahk/_sync/engine.py
requirements-dev.txt

Fixes a problem where the `which` argument in `show_tooltip` was not passed to AHK. This means this argument was effectively ignored in AHK v1 and causes an error in AHK v2. This PR fixes the oversight.
Resolves #361

gh-361 fix bug in show_tooltip that silently omitted `which` argument

---

ahk/_async/transport.py
ahk/_constants.py
ahk/_sync/transport.py
ahk/templates/daemon-v2.ahk
requirements-dev.txt

ensures that arguments are correctly parsed as numbers when provided and fixes a problem in AHKv2 where the tooltip window creation may be blocked by returning to the blocking daemon input loop until the next command invocation
Previously, an error may be thrown when `x` or `y` parameters were not provided when using AHK v2 and tooltips for successful calls may be delayed until a subsequent command is received.
Completes the fix from #362 and fully resolves #361
This also reverts a change that pinned `mypy` to 1.13.0 to avoid new typing issues that arose with abstract methods when upgrading `mypy` to 1.14.1 -- the typing issues were resolved and mypy has been unpinned.

fix show_tooltip for AHK v2

---

ahk/_async/engine.py
ahk/_constants.py
ahk/_sync/engine.py
ahk/templates/daemon-v2.ahk
ahk/templates/daemon.ahk

Adds `coord_mode` keyword argument to `mouse_move` allowing the coordinate mode to be changed for individual function invocations (rather than requiring a persistent global state change via `set_coord_mode`)
Additionally, this change also fixes a bug that occurs when using AHK v1 where the `send_mode` keyword argument was being ignored. Now the `send_mode` argument is respected as it is when using AHK v2.

add coord_mode keyword arg for mouse_move
